### ISSUE TITLE
Done the process but bandwidth is same

### ISSUE THREAD

**Issue by ajai-sandy** [Morhaus/dispatch-proxy#46]
Hi,
I have followed every step carefully and started the dispatch, but to my surprise the speed seems to be same. I tried downloading multiple videos and upload files simultaneously but the bandwidth remains the same of my lan which is 25mbps. Even did a speed test and shows a less speed when dispatch starts.

I have connected with the following in my lap
1) LAN - 25mbps (Sharing Galaxy Broadband)
2) Wifi - 15mbps (Airtel Broadband)

Now it should have the combine speed of 40mbps, I tested using speedtest and downloded+uploaded files but the banwidth seems to reduce rather than increase

Any solution for my problem.
Thanks in advance

Screenshot of my speedtest:
------------------------------------

![speed test](https://cloud.githubusercontent.com/assets/6812847/7364962/a1146e36-eda9-11e4-8872-9e859c52d126.jpg)

**Comment by zekesonxx** [comment]
DIspatch balances TCP connections, it can't split them up between lines. If you test a threaded download, like a torrent or Steam, you'll see the speed increases.

Speedtest is a single-threaded test, meaning that it can't benefit from dispatch. In the case of your test, the connection got balanced to your Wi-Fi connection, which is why it only had that speed.

**Comment by ajai-sandy** [comment]
Thank you for your answer, will check it.
