### ISSUE TITLE
vpn setup

### ISSUE THREAD

**Issue by martingg88** [Morhaus/dispatch-proxy#48]
is it possible to combine internet connection speed in VPN environment?

**Comment by Morhaus** [comment]
I've experimented a bit with it but I couldn't find an OpenVPN configuration that allowed for multiple network interfaces to communicate with a single VPN connection. I've also tried running two VPN connections at the same time, each bound to a single network interface, and using dispatch-proxy to balance between the two, but had no success with it.

I'm open to ideas if you have any.

**Comment by martingg88** [comment]
as with VPN service, is it able to leverage VPS internet connections without affect our local internet speed? 

Do you have any idea how traffic route in VPN environment?

**Comment by rlindsberg** [comment]
> as with VPN service, is it able to leverage VPS internet connections without affect our local internet speed?
I don't really understand what you mean. But a VPN won't affect local connections since usually they are not routed through VPN.

> Do you have any idea how traffic route in VPN environment?
I can only answer about Mac OS X. When you have more than two connections, the system will only use the one on the top. You configure that connection with dispatch proxy which will stop and take over the http connections and balance them using two or more connections, usually Ethernet and Wi-Fi.

I hope it answered your question and feel free to reopen this issue if you are still confused or have any idea about how to dispatch two VPN connections.
