### ISSUE TITLE
Bond Multiple Android Hotspots into One? 

### ISSUE THREAD

**Issue by tomatopeel** [Morhaus/dispatch-proxy#80]
Hello,

Just found this when searching the internet, my use case is that I'm in a less developed part of the world with slower internet and it would be great to be able to bond a bunch of Android hotspots together into a single hotspot.

Is this possible with this software? I'm guessing not (since it's Node.js) but thought I'd ask anyway, sorry to waste any time.

**Comment by Morhaus** [comment]
If your computer has multiple network interfaces that can each connect to one wi-fi network, you'll be able to use them all simultaneously.

Otherwise, if you want to create a new hotspot that proxies those hotspots, I'm not quite sure how you'd proceed, but I'm confident it's possible. For instance, you might be able to setup a raspberry pi running this software.

**Comment by rlindsberg** [comment]
Please refer to the documentation at https://github.com/Morhaus/dispatch-proxy/tree/master/docs.
